window.IMAGE_GROUP_REVIEW_MANIFEST = [
  'image-group-review-images/C29 - 01.jpeg',
  'image-group-review-images/C29 - 02.jpeg',
  'image-group-review-images/C29 - 03.jpeg',
  'image-group-review-images/C29 - 04.jpeg',
  'image-group-review-images/C29 - 05.jpeg',
  'image-group-review-images/C29 - 06.jpeg',
  'image-group-review-images/C29 - 07.jpeg',
  'image-group-review-images/C29 - 08.jpeg',
  'image-group-review-images/C29 - 09.jpeg',
  'image-group-review-images/Diya -  1.jpeg',
  'image-group-review-images/Diya - 2.jpeg',
  'image-group-review-images/Diya - 3.jpeg',
  'image-group-review-images/Diya - 4.jpeg',
  'image-group-review-images/Diya - 5.jpeg',
  'image-group-review-images/Diya - 6.jpeg',
  'image-group-review-images/Dream Catcher - 01.jpeg',
  'image-group-review-images/Dream Catcher - 02.jpeg',
  'image-group-review-images/Dream Catcher - 03.jpeg',
  'image-group-review-images/Dream Catcher - 04.jpeg',
  'image-group-review-images/J30 - 01.jpeg',
  'image-group-review-images/J30 - 02.jpeg',
  'image-group-review-images/J30 - 03.jpeg',
  'image-group-review-images/J30 - 04.jpeg',
  'image-group-review-images/J30 - 05.jpeg',
  'image-group-review-images/J30 - 06.jpeg',
  'image-group-review-images/J30 - 07.jpeg',
  'image-group-review-images/J30 - 08.jpeg',
  'image-group-review-images/J30 - 09.jpeg',
  'image-group-review-images/J30 - 10.jpeg',
  'image-group-review-images/J30 - 11.jpeg',
  'image-group-review-images/J30 - 12.jpeg',
  'image-group-review-images/J30 - 13.jpeg',
  'image-group-review-images/J30 - 14.jpeg',
  'image-group-review-images/K25 - 01 .jpeg',
  'image-group-review-images/K25 - 02 .jpeg',
  'image-group-review-images/K25 - 03 .jpeg',
  'image-group-review-images/K25 - 04 .jpeg',
  'image-group-review-images/K25 - 05 .jpeg',
  'image-group-review-images/K25 - 06 .jpeg',
  'image-group-review-images/K25 - 07 .jpeg',
  'image-group-review-images/K25 - 08 .jpeg',
  'image-group-review-images/K25 - 09 .jpeg',
  'image-group-review-images/K25 - 10 .jpeg',
  'image-group-review-images/N25 - 01.jpeg',
  'image-group-review-images/N25 - 02.jpeg',
  'image-group-review-images/N25 - 03.jpeg',
  'image-group-review-images/N30 - 01.jpeg',
  'image-group-review-images/N30 - 02.jpeg',
  'image-group-review-images/N30 - 03.jpeg',
  'image-group-review-images/N30 - 04.jpeg',
  'image-group-review-images/N30 - 05.jpeg',
  'image-group-review-images/N30 - 06.jpeg',
  'image-group-review-images/N30 - 07.jpeg',
  'image-group-review-images/N30 - 08.jpeg',
  'image-group-review-images/N30 - 09.jpeg',
  'image-group-review-images/N30 - 10.jpeg',
  'image-group-review-images/N30 - 11.jpeg',
  'image-group-review-images/N30 - 12.jpeg',
  'image-group-review-images/N30 - 13.jpeg',
  'image-group-review-images/N30 - 14.jpeg',
  'image-group-review-images/N30 - 15.jpeg',
  'image-group-review-images/Pluto - 01.jpeg',
  'image-group-review-images/Pluto - 02.jpeg',
  'image-group-review-images/Pluto - 03.jpeg',
  'image-group-review-images/Pluto - 04.jpeg',
  'image-group-review-images/Pluto - 05.jpeg',
  'image-group-review-images/Pluto - 06.jpeg',
  'image-group-review-images/Pluto - 07.jpeg',
  'image-group-review-images/Pluto - 08.jpeg',
  'image-group-review-images/Pluto - 09.jpeg',
  'image-group-review-images/Pluto - 10.jpeg',
  'image-group-review-images/Pluto - 11.jpeg',
  'image-group-review-images/Pluto - 12.jpeg',
  'image-group-review-images/Pluto - 13.jpeg',
  'image-group-review-images/Pluto - 14.jpeg',
  'image-group-review-images/Pluto - 15.jpeg',
  'image-group-review-images/RockyIndia - 01.jpeg',
  'image-group-review-images/RockyIndia - 02.jpeg',
  'image-group-review-images/RockyIndia - 03.jpeg',
  'image-group-review-images/RockyIndia - 04.jpeg'
];
